"""Turn a backend's output stream into evidence that work is happening.

Liveness alone is a weak signal: a process printing progress dots looks
exactly like one producing research. Codex's `--json` stream carries the real
thing -- `item.completed` for each unit of work, and `turn.completed` with a
token `usage` block -- so a job can report tokens produced rather than merely
"still breathing".

That is what makes it safe to stop killing long jobs on a wall clock. A job
emitting tokens is working, however long it takes; a job emitting nothing is
the one to kill.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field


@dataclass
class Progress:
    """Accumulated evidence of work from one backend invocation."""

    lines: int = 0
    bytes_seen: int = 0
    items: int = 0            # item.completed -- discrete units of work
    turns: int = 0            # turn.completed
    output_tokens: int = 0    # tokens the model actually produced
    reasoning_tokens: int = 0
    input_tokens: int = 0
    last_event: str | None = None

    # Fields we sum across turns; codex reports usage per completed turn.
    _seen_usage: list = field(default_factory=list, repr=False)

    @property
    def produced_tokens(self) -> int:
        """Tokens generated by the model -- the load-bearing work signal."""
        return self.output_tokens + self.reasoning_tokens

    def feed(self, chunk: str) -> None:
        """Consume one line of backend output."""
        self.lines += 1
        self.bytes_seen += len(chunk)
        text = chunk.strip()
        if not text.startswith("{"):
            return
        try:
            event = json.loads(text)
        except ValueError:
            return
        if not isinstance(event, dict):
            return
        kind = event.get("type")
        if isinstance(kind, str):
            self.last_event = kind
        if kind == "item.completed":
            self.items += 1
        elif kind == "turn.completed":
            self.turns += 1
            usage = event.get("usage")
            if isinstance(usage, dict):
                self._seen_usage.append(usage)
                self.output_tokens += int(usage.get("output_tokens") or 0)
                self.reasoning_tokens += int(usage.get("reasoning_output_tokens") or 0)
                self.input_tokens += int(usage.get("input_tokens") or 0)

    def summary(self) -> str:
        return (
            f"{self.produced_tokens} tokens, {self.items} items, "
            f"{self.turns} turns, {self.bytes_seen} bytes"
            + (f", last={self.last_event}" if self.last_event else "")
        )

    def as_metadata(self) -> dict:
        return {
            "produced_tokens": self.produced_tokens,
            "output_tokens": self.output_tokens,
            "reasoning_tokens": self.reasoning_tokens,
            "input_tokens": self.input_tokens,
            "items": self.items,
            "turns": self.turns,
            "lines": self.lines,
            "bytes": self.bytes_seen,
            "last_event": self.last_event,
        }
